---
name: Publish
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - uses: Gr1N/setup-poetry@v7

      - name: Set version
        run: poetry version $(git describe --tags --abbrev=0)

      - name: Build wheel
        run: poetry build

      - uses: docker/setup-qemu-action@v1.2.0

      - uses: docker/setup-buildx-action@v1.6.0

      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Find hass version
        id: hass_version
        run: |
          hass_version=$(poetry show homeassistant | grep '^version' \
            | cut -d':' -f 2 | awk '{$1=$1};1')
          echo ::set-output name=version::$hass_version

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
            prefix=${{ steps.hass_version.outputs.version }}-,onlatest=false

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/386,linux/arm64/v8,linux/arm/v6 # yamllint disable-line rule:line-length
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            HASS_VERSION=${{ steps.hass_version.outputs.version }}

      - name: Publish to PyPI
        run: poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
